title: Poplar Development
author: Chris (chris at poplars.dev)
description: Quality customizations to Sage 300 built using Orchid Extender.

show_excerpts: false 

theme: jekyll-theme-minimal
logo: assets/img/poplar_gray.png

collections:
    opensource:
        output: true
        sort_by: order
    customizations:
        output: true
        sort_by: order

google_analytics: G-78HPF3112N

defaults:
    - scope:
        path: ""
        type: "customizations"
      values:
        layout: "customization"
        order: 5
        apps: 
        views:
        screens:
        format: "tailored"
        monthly_cost: 0
        presentation: 
        demo:
        docs:
        webscreen:
        excerpt_separator: "<!--more-->"
